.TH SIMEIS 1 "24 Juin 2026" "1.0.0" "Simeis Manual"
.SH NAME
simeis \- Serveur d'infrastructure et gestionnaire d'aventuriers
.SH SYNOPSIS
.B simeis
.SH DESCRIPTION
.B simeis
est un service d'arrière-plan optimisé en Rust conçu dans le cadre du module CI/CD de l'Ynov Nantes.
.SH FILES
.TP
.I /etc/systemd/system/simeis.service
Fichier d'unité Systemd pour la gestion du démon.
.SH AUTHOR
Evan