name: Branch Guard

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Analyse de la situation
        id: gatekeeper
        run: |
          TARGET="${{ github.base_ref }}"
          SOURCE="${{ github.head_ref }}"
          
          echo "Cible : $TARGET"
          echo "Source : $SOURCE"

          # CONDITION : Si la cible est une release
          if [[ "$TARGET" == release/* ]]; then
            # On vérifie si la source est autorisée
            if [[ "$SOURCE" == "main" ]] || [[ "$SOURCE" == bug/* ]]; then
              echo "status=ok" >> $GITHUB_OUTPUT
            else
              echo "status=fail" >> $GITHUB_OUTPUT
            fi
          else
            # Si on ne cible pas une release, tout est autorisé par ce workflow
            echo "status=ok" >> $GITHUB_OUTPUT
          fi

      - name: Fermeture si non conforme
        if: steps.gatekeeper.outputs.status == 'fail'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: |
            ❌ **PR Refusée** : Une branche `release/*` ne peut accepter du code que depuis `main` ou `bug/*`.