name: Check TODOs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master
      - develop

jobs:
  check-todos:
    name: Analyse des commentaires TODO
    runs-on: ubuntu-latest
    
    steps:
      # Seule action du marketplace officiellement autorisée dans le sujet
      - name: Checkout code
        uses: actions/checkout@v4
      
      # On utilise directement le Python de la machine virtuelle sans passer par une action du marketplace
      - name: Check TODOs Status
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x check_todos.py
          python3 check_todos.py