name: Simeis CI

on:
  pull_request:
    branches: [ main, "release/*" ]
  push:
    branches: [ main ]

jobs:
  # --- 1. JOB LINT (Python & Rust Format) ---
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Ruff
        run: pip install ruff
      - name: Python Linting
        run: ruff check .
      - name: Rust Format Check
        run: cargo fmt --check

  # --- 2. JOB TEST (Unit Tests) ---
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust - Tests unitaires
        run: make test

  # --- 3. JOB BUILD DEV (Compilation simple) ---
  build_dev:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Développement - Check & Build
        run: make build

  # --- 4. JOB QUALITY (Clippy & Advanced Checks) ---
  quality:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust - Clippy
        run: cargo clippy -- -D warnings

  # --- 5. JOB PRODUCTION (Merge dans main uniquement) ---
  release_and_doc:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Typst
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xvf typst-x86_64-unknown-linux-musl.tar.xz
          sudo cp typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
      - name: Compilation Release
        run: make release
      - name: Compilation Documentation
        run: make doc